name: Test

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - nest-version: "7"
          - nest-version: "8"
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install Nest
        env:
          NEST_VERSION: ${{ matrix.nest-version }}
        run: npm install @nestjs/common@$NEST_VERSION @nestjs/core@$NEST_VERSION @nestjs/testing@$NEST_VERSION

      - name: Install platform-express
        if: matrix.nest-version =~ '^\^(6|7).*'
        env:
          NEST_VERSION: ${{ matrix.nest-version }}
        run: npm install @nestjs/platform-express@$NEST_VERSION

      - name: npm test
        run: npm test
      - name: npm run build
        run: npm run build

